<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <title><?php echo 'title'; ?></title>
  <meta name="description" content="<?php echo 'tagline';?>" />
  <meta name="author" content="<?php echo 'author'; ?>">
  <meta charset="UTF-8">
  <link rel="icon" href="<?php echo $application->configCommon['assetUrl'] . 'document/images/favicon-' . 'blue' . '.png'; ?>" type="image/x-icon">
  <!-- Mobile -->
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href='<?php echo $application->configCommon['assetUrl']; ?>document/css/style.css' rel='stylesheet' type='text/css'>

  <link href='<?php echo $application->configCommon['assetUrl'] . 'document/css/theme_' . 'blue' . '.css'; ?>' rel='stylesheet' type='text/css'>

</head>
<body>

<div class="navbar navbar-fixed-top hidden-print">
  <div class="container">
    <a class="brand navbar-brand pull-left" href="<?php echo 'indexurl'; ?>"><?php echo 'project_title'; ?></a>
    <p class="navbar-text pull-right">Generated by <a href="http://daux.io">Daux.io</a></p>
  </div>
</div>
<a href="https://github.com/<?php echo 'repo'; ?>" target="_blank" id="github-ribbon" class="hidden-print">
  <img src="<?php echo $application->configCommon['assetUrl']; ?>document/images/github_fork.png" alt="Fork me on GitHub">
</a>


<?php echo $contentLayout; ?>

<?php $application->render('common/js_base', array('application' => $application)); ?>
<script src="<?php echo $application->configCommon['assetUrl']; ?>document/js/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<script src="<?php echo $application->configCommon['assetUrl']; ?>document/js/editor.js"></script>
<script src="<?php echo $application->configCommon['assetUrl']; ?>document/js/custom.js"></script>
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</body>
</html>

