<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <title>Getting Started</title>
    <meta name="description" content="The Easiest Way To Document Your Project" />
    <meta name="author" content="Justin Walsh">
    <meta charset="UTF-8">
    <link rel="icon" href="//localhost/test/daux.io/templates/default/themes/daux-blue/img/favicon-blue.png" type="image/x-icon">
    <!-- Mobile -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font -->
    <link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700&subset=latin,cyrillic-ext,cyrillic' rel='stylesheet' type='text/css'>
    <!-- CSS -->
    <link href='//localhost/test/daux.io/templates/default/themes/daux-blue/css/daux-blue.css' rel='stylesheet' type='text/css'>
</head>
<body>
  <?php if ($homepage) { ?>
  <!-- Homepage -->
    <div class="navbar navbar-fixed-top hidden-print">
      <div class="container">
        <a class="brand navbar-brand pull-left" href="<?php echo $index; ?>"><?php echo $project_title; ?></a>
        <p class="navbar-text pull-right">Generated by <a href="http://daux.io">Daux.io</a></p>
      </div>
    </div>
    <?php if ($params['repo']) { ?>
      <a href="https://github.com/<?php echo $params['repo']; ?>" target="_blank" id="github-ribbon" class="hidden-print"><img src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
    <?php } ?>

    <div class="homepage-hero well container-fluid">
      <div class="container">
        <div class="row">
          <div class="text-center col-sm-12">
            <?php if ($page['tagline']) echo '<h2>' . $page['tagline'] . '</h2>'; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <?php if ($params['image']) echo '<img class="homepage-image img-responsive" src="' . $params['image'] . '" alt="' . $project_title . '">'; ?>
          </div>
        </div>
      </div>
    </div>

    <div class="hero-buttons container-fluid">
      <div class="container">
        <div class="row">
          <div class="text-center col-sm-12">
            <?php
              if ($params['repo']) echo '<a href="https://github.com/' . $params['repo'] . '" class="btn btn-secondary btn-hero">View On GitHub</a>';
              foreach ($entry_page as $key => $node) echo '<a href="' . $node . '" class="btn btn-primary btn-hero">' . $key . '</a>';
            ?>
          </div>
        </div>
      </div>
    </div>

    <div class="homepage-content container-fluid">
      <div class="container">
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <?php echo $page['content'];?>
          </div>
        </div>
      </div>
    </div>

  <?php } else { ?>
    <!-- Docs -->
    <?php if ($params['repo']) { ?>
      <a href="https://github.com/<?php echo $params['repo']; ?>" target="_blank" id="github-ribbon" class="hidden-print"><img src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
    <?php } ?>
    <div class="container-fluid fluid-height wrapper">
      <div class="navbar navbar-fixed-top hidden-print">
        <div class="container-fluid">
          <a class="brand navbar-brand pull-left" href="<?php echo $index;?>"><?php echo $project_title; ?></a>
          <p class="navbar-text pull-right">Generated by <a href="http://daux.io">Daux.io</a></p>
        </div>
      </div>
      <div class="row columns content">
        <div class="left-column article-tree col-sm-3 hidden-print">
          <!-- For Mobile -->
          <div class="responsive-collapse">
            <button type="button" class="btn btn-sidebar" id="menu-spinner-button">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="sub-nav-collapse" class="sub-nav-collapse">
            <!-- Navigation -->
            <?php
              if ($page['language'] !== '') echo $this->get_navigation($tree->value[$page['language']], $page['language'], $params['request'], $base_page, $params['mode']);
              else echo $this->get_navigation($tree, '', $params['request'], $base_page, $params['mode']);
            ?>
            <?php if (!empty($params['links']) || !empty($params['twitter'])) { ?>
              <div class="well well-sidebar">

                <!-- Links -->
                <?php foreach ($params['links'] as $name => $url) echo '<a href="' . $url . '" target="_blank">' . $name . '</a><br>'; ?>
                <?php if ($params['toggle_code']) echo '<a href="#" id="toggleCodeBlockBtn" onclick="toggleCodeBlocks();">Show Code Blocks Inline</a><br>'; ?>

                <!-- Twitter -->
                <?php foreach ($params['twitter'] as $handle) { ?>
                  <div class="twitter">
                    <hr/>
                    <iframe allowtransparency="true" frameborder="0" scrolling="no" style="width:162px; height:20px;" src="https://platform.twitter.com/widgets/follow_button.html?screen_name=<?php echo $handle;?>&amp;show_count=false"></iframe>
                  </div>
                <?php } ?>
              </div>
            <?php } ?>
          </div>
        </div>
        <div class="right-column <?php echo ($params['float']?'float-view':''); ?> content-area col-sm-9">
          <div class="content-page">
            <article>
              <?php if ($params['date_modified']) { ?>
                <div class="page-header sub-header clearfix">
                  <h1><?php
                      if ($page['breadcrumbs']) echo $this->get_breadcrumb_title($page, $base_page);
                      else echo $page['title'];
                    ?>
                    <?php if ($page['file_editor']) echo '<a href="javascript:;" id="editThis" class="btn">Edit this page</a>'; ?>
                  </h1>
                  <span style="float: left; font-size: 10px; color: gray;">
                    <?php echo date("l, F j, Y", $page['modified_time']);?>
                  </span>
                  <span style="float: right; font-size: 10px; color: gray;">
                    <?php echo date("g:i A", $page['modified_time']);?>
                  </span>
                </div>
              <?php } else { ?>
                <div class="page-header">
                  <h1><?php
                      if ($page['breadcrumbs']) echo $this->get_breadcrumb_title($page, $base_page);
                      else echo $page['title'];
                    ?>
                    <?php if ($page['file_editor']) echo '<a href="javascript:;" id="editThis" class="btn">Edit this page</a>'; ?>                  </h1>
                </div>
              <?php } ?>

              <?php echo $page['content']; ?>
              <?php if ($page['file_editor']) { ?>
                <div class="editor<?php if(!$params['date_modified']) echo ' paddingTop'; ?>">
                  <h3>You are editing <?php echo $page['path']; ?>&nbsp;<a href="javascript:;" class="closeEditor btn btn-warning">Close</a></h3>
                  <div class="navbar navbar-inverse navbar-default navbar-fixed-bottom" role="navigation">
                    <div class="navbar-inner">
                      <a href="javascript:;" class="save_editor btn btn-primary navbar-btn pull-right">Save file</a>
                    </div>
                  </div>
                  <textarea id="markdown_editor"><?php echo $page['markdown'];?></textarea>
                  <div class="clearfix"></div>
                </div>
              <?php } ?>
            </article>
          </div>
        </div>
      </div>
    </div>
  <?php } ?>


</body>
</html>
